import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageJsonPath = path.resolve(__dirname, "..", "package.json");
const outputFile = path.resolve(__dirname, "..", "src", "version.generated.ts");

async function generate() {
  const raw = await fs.readFile(packageJsonPath, "utf-8");
  const pkg = JSON.parse(raw);
  if (typeof pkg.version !== "string" || pkg.version.length === 0) {
    throw new Error(
      `package.json: "version" must be a non-empty string, got ${JSON.stringify(pkg.version)}`
    );
  }

  // Single source of truth for the runtime version string surfaced at the
  // root `/` discovery endpoint. Regenerated from package.json on every
  // `npm run generate` (chained from `npm run build`); CI fails if this
  // file drifts from the package.json `version`. Keeps the deployed
  // `https://doaas.dev/` payload in lockstep with releases.
  const output = `// This file is autogenerated by scripts/generate-version.mjs
/* eslint-disable */
export const VERSION = ${JSON.stringify(pkg.version)};
`;

  await fs.writeFile(outputFile, output, "utf-8");
  console.log(`Generated ${outputFile} with VERSION="${pkg.version}".`);
}

generate().catch((err) => {
  console.error(err);
  process.exit(1);
});
