// This file is autogenerated by scripts/generate-endpoints.mjs
/* eslint-disable */
export const ENDPOINTS = {
  "alignment": {
    "name": "alignment",
    "description": "Team alignment messages",
    "modes": [
      "normal",
      "corporate",
      "chaos",
      "sarcastic"
    ],
    "examples": [
      "Let's align on project goals this week.",
      "Ensure everyone understands the roadmap."
    ],
    "examplesByMode": {
      "normal": [
        "Let's align on project goals this week.",
        "Ensure everyone understands the roadmap.",
        "Sync up with stakeholders regularly.",
        "Everyone on the same page? Great, let's build.",
        "Alignment first, execution second.",
        "Quick sync before we go heads-down.",
        "Let's get on the same page. Then execute.",
        "Goals clear? Great. Let's ship.",
        "Quick alignment before the sprint.",
        "Everyone know the priorities? Good.",
        "Sync on scope before we build.",
        "Align on the plan. Then run.",
        "Same page? Same page. Go.",
        "Goals aligned. Let's do this.",
        "Quick check: we're building the right thing? Good.",
        "Stakeholders aligned. We're aligned. Go.",
        "Priorities locked. Team aligned. Execute.",
        "Alignment done. Questions? No? Ship.",
        "We're aligned. Document it. Then build.",
        "Goals set. Team aligned. Let's go."
      ],
      "corporate": [
        "We need to ensure strategic alignment across Q3 objectives.",
        "Stakeholder alignment is critical for delivery.",
        "Let's sync our KPIs with the broader org.",
        "Cross-functional alignment meeting scheduled.",
        "Executive alignment achieved; proceed with initiative.",
        "Ensure RACI matrix alignment before kickoff.",
        "Stakeholder alignment critical for delivery.",
        "Sync KPIs with the broader org.",
        "Executive alignment achieved; proceed.",
        "RACI matrix alignment before kickoff.",
        "Program alignment with portfolio priorities.",
        "Stakeholder sign-off required; alignment meeting set.",
        "OKR alignment with company goals.",
        "Board alignment on initiative; proceed.",
        "Cross-team alignment on dependencies.",
        "Executive alignment documented; green light.",
        "Governance alignment confirmed; initiative approved.",
        "Strategic alignment complete; execution authorized."
      ],
      "chaos": [
        "We're aligned. On chaos. Everyone good with that?",
        "Alignment achieved: we're all confused together.",
        "Synced. No one knows what we're building. Perfect.",
        "Alignment complete. Three different interpretations. Ship it.",
        "We aligned in the hallway. Or was that a fever dream?",
        "Alignment: everyone agreed to disagree. Moving on.",
        "We're aligned. I think. I'm not sure on what.",
        "Synced. We have three versions of the plan. All correct.",
        "Alignment: we said the same words. Different meanings. Ship it.",
        "We're aligned. The doc says so. No one read the doc.",
        "Alignment complete. We'll discover what we meant later.",
        "Synced. We're building something. Probably. Good enough.",
        "Alignment: we nodded. We're not sure we agreed. Proceeding.",
        "We're aligned. On needing another alignment meeting. Soon."
      ],
      "sarcastic": [
        "Let's align. Again. For the 47th time this sprint.",
        "Strategic alignment: my calendar says yes, my soul says no.",
        "We're aligned. I have no idea what we aligned on.",
        "Alignment meeting: 2 hours, zero decisions. Success.",
        "Fully aligned. My interpretation is the right one.",
        "Synergy achieved. Synergy is still not a real word.",
        "Let's align. My notes say one thing. Yours say another. Both right.",
        "Alignment: we achieved it. We think. The deck says so.",
        "We're aligned. I'll know for sure after the next alignment meeting.",
        "Strategic alignment: we have a slide. The slide has words. We're good.",
        "Aligned. On something. Possibly the same thing. Proceeding.",
        "Alignment complete. We have consensus. On having another meeting.",
        "We're aligned. The strategy is clear. To someone. Somewhere.",
        "Synergy: achieved. Meaning: TBD. Confidence: high. Somehow.",
        "Alignment done. We're all saying the same thing. We think."
      ]
    }
  },
  "audit": {
    "name": "audit",
    "description": "Audit reminders and results",
    "modes": [
      "normal",
      "corporate",
      "security",
      "chaos",
      "sarcastic"
    ],
    "examples": [
      "Audit completed with no critical findings.",
      "Next audit scheduled for next quarter."
    ],
    "examplesByMode": {
      "normal": [
        "Audit completed with no critical findings.",
        "Next audit scheduled for next quarter.",
        "Please review audit logs for anomalies.",
        "Quarterly audit passed; minor findings documented.",
        "Audit trail complete; no unauthorized access.",
        "Internal audit wrapped; report in the shared drive.",
        "Audit logs retained per policy.",
        "Access audit: no exceptions found.",
        "Change audit: all changes documented.",
        "Security audit: no critical issues.",
        "Compliance audit: controls evidenced.",
        "Audit findings: minor; remediation in progress.",
        "Next audit: Q3; prepare evidence.",
        "Audit trail: complete and retained."
      ],
      "corporate": [
        "Internal audit has been completed; report available in the portal.",
        "Compliance audit cycle concludes end of month.",
        "Audit findings will be presented to the board.",
        "External audit passed; certification renewed.",
        "Audit remediation items tracked in Jira.",
        "Annual audit complete; no material weaknesses.",
        "Audit report published; stakeholders notified.",
        "Remediation plan approved; owners assigned.",
        "Board audit committee briefed.",
        "Audit cycle closed; next cycle planned.",
        "Certification renewed; valid 12 months.",
        "Audit trail documented; evidence retained.",
        "No material findings; control environment strong.",
        "Audit complete; management response on file."
      ],
      "security": [
        "Security audit identified no critical vulnerabilities.",
        "Pen test results are in; remediation tracked.",
        "Audit logs retained per policy; no unauthorized access.",
        "Vulnerability scan complete; patches applied.",
        "Access audit passed; least-privilege confirmed.",
        "Security posture assessment: acceptable risk.",
        "Pen test: findings remediated; retest scheduled.",
        "No critical or high vulnerabilities open.",
        "Access review complete; no over-privileged accounts.",
        "Secrets audit: no plaintext in repo.",
        "Security audit closed; follow-up in 6 months.",
        "Vulnerability management: within SLA.",
        "Security controls evidenced; audit passed.",
        "No security exceptions; controls operating."
      ],
      "chaos": [
        "Audit? We have logs. Somewhere. Probably.",
        "Audit completed. We're not sure what we audited.",
        "The auditors left. We're still recovering.",
        "Audit findings: yes. Details: TBD.",
        "We passed. Don't ask how. Don't.",
        "Audit trail exists. Finding it is the real audit.",
        "We have logs. They're in a system. We think.",
        "Audit: we had one. We passed. We're not sure how.",
        "The auditors were nice. We showed them the good stuff.",
        "Audit findings: we have them. We're addressing. Eventually.",
        "We passed. The bar was reasonable. We met it. Barely.",
        "Audit complete. Our documentation impressed. We're as surprised as you.",
        "Audit trail: it exists. Location: TBD. We're looking.",
        "We passed. Don't ask for the details. Please."
      ],
      "sarcastic": [
        "Audit passed. We showed them the good servers.",
        "No critical findings. We hid the critical stuff.",
        "Audit complete. Our documentation game is strong.",
        "Clean audit. The auditors were very understanding.",
        "Zero findings. Zero servers they could access.",
        "Audit: passed. Sanity: declining.",
        "We passed. We're as surprised as you are.",
        "Audit: clean. Our preparation: frantic. It worked.",
        "No findings. We had a checklist. We followed it. Mostly.",
        "Audit passed. The auditors liked our runbooks. We have runbooks?",
        "Clean bill of health. We'll celebrate. After we find the evidence.",
        "Zero critical findings. We showed them the right dashboards.",
        "Audit: passed. Our confidence: medium. Our relief: high.",
        "We passed. Don't ask how. We're not sure we know."
      ]
    }
  },
  "blame": {
    "name": "blame",
    "description": "Who/what caused the problem",
    "modes": [
      "normal",
      "chaos",
      "corporate",
      "security",
      "toxic",
      "sarcastic"
    ],
    "examples": [
      "It's not my fault, it was the network!",
      "Blame the last person who touched the code."
    ],
    "examplesByMode": {
      "normal": [
        "It's DNS. Again.",
        "Caching lied to us.",
        "It's not my fault, it was the network!",
        "Blame the last person who touched the code.",
        "Third-party API changed without notice.",
        "Race condition. Classic.",
        "It's the network. It's always the network.",
        "Cache invalidation. Hard problem.",
        "Third-party outage. Not us.",
        "Timeout on the upstream service.",
        "Load balancer had a moment.",
        "Database connection pool. Again.",
        "CDN edge node misbehaving.",
        "Kubernetes did something. We're not sure what.",
        "Out of memory. The server's, not mine.",
        "Disk full. Logs. Always the logs.",
        "SSL certificate expired. Who's job was that?",
        "Config drift. Classic.",
        "Deployment race. Two deploys, one winner.",
        "Timeout. The request is still thinking. Somewhere."
      ],
      "chaos": [
        "Cosmic rays hit the load balancer. Good luck.",
        "Mercury is in retrograde. Blame physics.",
        "The server is down because someone forgot to pay the bill.",
        "A butterfly flapped its wings in prod. Probably.",
        "The hamster powering the server needed a break.",
        "Sunspots. Definitely sunspots.",
        "The gremlins are back. We thought we'd evicted them.",
        "Phase of the moon. Deploy calendar says so.",
        "The data center had a feeling. We're respecting it.",
        "Someone unplugged something. We don't know who. Or what.",
        "The backup power kicked in. It's shy. Didn't announce.",
        "A butterfly in Brazil. Chaos theory. Look it up.",
        "The hamster needed a break. We're supportive.",
        "Mercury is still in retrograde. Blame the cosmos.",
        "The cloud had a thought. It was a bad thought.",
        "Electromagnetic interference. From where? Yes.",
        "The server got lonely. It's emotional.",
        "Bit flip. Cosmic rays. Same thing. Probably.",
        "The load balancer took a nap. Unplanned.",
        "The network had opinions. Strong opinions."
      ],
      "corporate": [
        "This appears to be an upstream dependency issue.",
        "Unexpected vendor behavior impacted delivery.",
        "External factor outside our control.",
        "Prior ownership did not document this.",
        "Cross-team dependency introduced the variance.",
        "Legacy system interaction; not in current scope.",
        "Upstream dependency issue; vendor notified.",
        "Unexpected vendor behavior; impact documented.",
        "External factor; outside our control.",
        "Prior ownership; documentation gap.",
        "Cross-team dependency; variance introduced.",
        "Third-party API change; no advance notice.",
        "Vendor SLA breach; escalation in progress.",
        "Upstream timeline slip; we're blocked.",
        "External system degradation; we're impacted.",
        "Legacy integration; not in current roadmap.",
        "Dependency update introduced regression.",
        "Vendor communication gap; following up.",
        "Upstream change; we weren't in the loop.",
        "External dependency; mitigation in progress."
      ],
      "security": [
        "Misconfigured IAM did it. As usual.",
        "An expired certificate chose violence.",
        "Someone committed secrets to the repo. Again.",
        "Default credentials. Still default. In prod.",
        "Shadow IT deployed something. We're still finding it.",
        "That service account had too much power. Oops.",
        "Unencrypted channel. We're fixing. Again.",
        "Missing MFA on that account. We know.",
        "Credentials in the log. We've rotated. Again.",
        "Over-permissioned role. Cleanup in progress.",
        "Hardcoded secret. In the code. We found it. Again.",
        "Patching lag. Critical CVE. We're on it.",
        "That API key was in the client. We've revoked.",
        "Security review skipped. We're doing it now."
      ],
      "toxic": [
        "Obviously the last person who touched it.",
        "Probably the intern. Or you.",
        "Who wrote this? Oh. You. That explains it.",
        "The person who merged without review. You know who you are.",
        "Someone who clearly doesn't test their code.",
        "The on-call who slept through the alert. Allegedly.",
        "The person who said it worked on their machine.",
        "Whoever skipped the review. You know who you are.",
        "The one who deployed on Friday. We have a list.",
        "Someone who thought staging was prod. Or didn't check.",
        "The person who didn't run the tests. We know.",
        "Whoever left the debug log in. In prod.",
        "The one who said it was a quick fix. It wasn't.",
        "Obviously not me. I would never. Except that one time."
      ],
      "sarcastic": [
        "Surely not the person who merged without testing.",
        "Must be the cloud. It's always the cloud.",
        "Couldn't possibly be the 47th hotfix this week.",
        "Clearly the ghost in the machine. Very cooperative ghost.",
        "Probably user error. Users are the worst.",
        "It's a feature. A very aggressive feature.",
        "Must be the cache. The cache is a scapegoat. A reliable one.",
        "Surely not the deploy we did 10 minutes ago.",
        "Couldn't be the config change. The config is innocent. Probably.",
        "Clearly the network. The network is always guilty.",
        "Probably a race condition. We have a lot of those.",
        "Must be the dependency. We have 400. One of them.",
        "Surely not our code. Our code is perfect. We think.",
        "It's the system. The system is complicated. So we blame it."
      ]
    }
  },
  "burnout": {
    "name": "burnout",
    "description": "Burnout awareness and advice",
    "modes": [
      "normal",
      "wholesome",
      "chaos",
      "sarcastic"
    ],
    "examples": [
      "Remember to take breaks and rest.",
      "It's okay to ask for help."
    ],
    "examplesByMode": {
      "normal": [
        "Remember to take breaks and rest.",
        "It's okay to ask for help.",
        "Prevent burnout by managing workload.",
        "Step away from the screen. Your eyes will thank you.",
        "Deferred work is not deleted work. Pace yourself.",
        "Sustainable pace beats heroic sprints.",
        "Take breaks. Your brain needs them.",
        "It's okay to say no to more work.",
        "Rest is part of the job. Really.",
        "Step away. The code will be there.",
        "Pace yourself. Marathons, not sprints. Literally.",
        "Ask for help before you're drowning.",
        "Boundaries are healthy. Set them.",
        "Sleep matters. So does lunch.",
        "You're not a machine. Act accordingly.",
        "Delegate when you can. It's not weakness.",
        "Time off is not optional. Take it.",
        "Sustainable pace wins. Every time.",
        "Your health is non-negotiable.",
        "Slow down. The work will still be there."
      ],
      "wholesome": [
        "You're doing great. It's okay to step back.",
        "Your health matters more than the sprint.",
        "Take that PTO. The code will still be here.",
        "You're enough. The tickets will wait.",
        "Rest isn't laziness. It's maintenance.",
        "Be kind to yourself. You've earned it.",
        "You matter. More than the deploy.",
        "It's okay to need a break. Take it.",
        "Your worth isn't your output. Remember that.",
        "Step back. Breathe. Then decide.",
        "You're allowed to have limits. Honor them.",
        "The team will survive without you for a week. Really.",
        "Rest. Recharge. You deserve it.",
        "Be gentle with yourself. You're trying."
      ],
      "chaos": [
        "You've been awake 32 hours. That's a personal best?",
        "Sleep is for people who aren't shipping. Jk. Sleep.",
        "The stack overflow isn't going to fix itself. But you need to.",
        "Your keyboard misses you. Go touch grass.",
        "Burnout speedrun: 47% complete. Please stop.",
        "You can't deploy from the ICU. Probably. Please rest.",
        "The pager can wait. Your sanity cannot. Probably.",
        "You've merged 47 PRs today. Tomorrow is a day too.",
        "Coffee is not a substitute for sleep. We've tried.",
        "The incident will be there tomorrow. So will you. Hopefully.",
        "Touch grass. Literally. The code will survive.",
        "Burnout: 60% complete. Achievement unlocked. Please stop.",
        "Your eyes are red. The pipeline is red. You need to log off.",
        "Rest. The deploy can wait. The deploy will always wait."
      ],
      "sarcastic": [
        "Self-care: responding to Slacks from the shower.",
        "Work-life balance: life is what happens between deploys.",
        "Boundaries: I don't check email. I check PagerDuty.",
        "Rest day: only 3 incident calls. Refreshed.",
        "Vacation: laptop in carry-on. For emergencies. All of them.",
        "Recharge: closed laptop. Opened laptop. Opened Slack.",
        "Self-care: I took a lunch. I ate at my desk. Progress.",
        "Boundaries: I only check Slack 47 times a day now.",
        "Rest: I didn't deploy this weekend. I thought about it.",
        "Work-life balance: life is the 5 minutes between meetings.",
        "Recharge: I closed one tab. Opened two. Net positive.",
        "Vacation: I'm out of office. My laptop is not.",
        "Self-care: I muted notifications. For an hour. It was scary.",
        "Rest: the pager didn't go off. I didn't trust it. I checked."
      ]
    }
  },
  "compliance": {
    "name": "compliance",
    "description": "Compliance reminders and checks",
    "modes": [
      "normal",
      "corporate",
      "security",
      "chaos",
      "sarcastic"
    ],
    "examples": [
      "Ensure GDPR compliance in data handling.",
      "Audit logs must be retained for 90 days."
    ],
    "examplesByMode": {
      "normal": [
        "Ensure GDPR compliance in data handling.",
        "Audit logs must be retained for 90 days.",
        "Follow company policy for access control.",
        "Data retention policy: 7 years for financial records.",
        "PII must be encrypted at rest and in transit.",
        "Compliance training due by end of quarter.",
        "GDPR: ensure data handling compliance.",
        "Audit logs retained 90 days minimum.",
        "Access control per company policy.",
        "Data retention: 7 years for financial records.",
        "PII encrypted at rest and in transit.",
        "Compliance training: complete by quarter end.",
        "Data classification required for new data.",
        "Vendor compliance check before onboarding.",
        "Right to deletion process documented.",
        "Privacy policy reviewed annually.",
        "Data processing agreements in place.",
        "Compliance attestation on file.",
        "Regulatory requirements in handbook.",
        "Control evidence retained per policy."
      ],
      "corporate": [
        "All changes must follow the compliance framework.",
        "Document retention policy applies to this dataset.",
        "Regulatory requirements are documented in the handbook.",
        "SOC 2 controls must be evidenced for this change.",
        "Compliance attestation required before go-live.",
        "Risk assessment completed; controls documented.",
        "Compliance review required for go-live.",
        "Governance framework applies.",
        "Stakeholder sign-off per compliance.",
        "Control environment documented.",
        "Audit trail for all changes.",
        "Compliance checklist complete.",
        "Regulatory alignment confirmed.",
        "Compliance gate passed; proceed."
      ],
      "security": [
        "Access must comply with least-privilege policy.",
        "Encryption at rest and in transit is mandatory.",
        "MFA required for production access.",
        "Secrets rotation every 90 days per policy.",
        "No production credentials in code or chat.",
        "Security review required for all data exports.",
        "Access per least-privilege policy.",
        "Secrets rotation every 90 days.",
        "No prod credentials in code or chat.",
        "Security review for all data exports.",
        "Data classification before sharing.",
        "Encryption keys managed per policy.",
        "Access review: quarterly.",
        "No PII in logs or chat.",
        "Security controls evidenced.",
        "Compliance check before release.",
        "Data handling per policy.",
        "Security sign-off on file."
      ],
      "chaos": [
        "Compliance: we have a checklist. Somewhere.",
        "GDPR? We have a privacy policy. It's 47 pages. Good luck.",
        "Audit logs: definitely logging something. Probably.",
        "We're compliant. The auditors haven't found us yet.",
        "Retention policy: we keep everything forever. Oops.",
        "Compliance is a state of mind. And also the law. Mostly the law.",
        "Compliance: we have a doc. It's in the drive. Somewhere.",
        "We're compliant. We think. The checklist was long.",
        "GDPR: we have a process. We follow it. Usually.",
        "Audit trail: we have logs. Many logs. Finding the right one: TBD.",
        "Compliance is a journey. We're on the journey. The map is unclear.",
        "We're compliant. The evidence is somewhere. We'll find it.",
        "Retention: we retain. We're not sure for how long. Long.",
        "Compliance: checked. The check was thorough. We think.",
        "We're compliant. Don't ask for the proof. It's in progress."
      ],
      "sarcastic": [
        "Fully compliant. Our documentation says so.",
        "We passed the compliance quiz. With a 62%.",
        "Yes, we're compliant. No, you can't see the evidence.",
        "Compliance: checked. Sanity: optional.",
        "All policies followed. The important ones. Mostly.",
        "Compliant since 2019. We think. The date might be wrong.",
        "We're compliant. The documentation is comprehensive. We've read the summary.",
        "Compliance: we have it. Evidence: we have it. Somewhere.",
        "We passed. The bar was reasonable. We met it. We think.",
        "Fully compliant. Don't ask for the audit trail. It's long.",
        "Compliance: achieved. Our definition of achieved: flexible.",
        "We're compliant. The checklist was 200 items. We did the important 150.",
        "Compliant. The proof is in the drive. The drive has 10,000 files.",
        "We're compliant. Trust us. Or don't. We have a doc. Somewhere."
      ]
    }
  },
  "deploy": {
    "name": "deploy",
    "description": "Deployment messages and instructions",
    "modes": [
      "normal",
      "chaos",
      "corporate",
      "devops",
      "sarcastic"
    ],
    "examples": [
      "Deployment started at 3 PM UTC.",
      "Rollback plan is ready if issues arise."
    ],
    "examplesByMode": {
      "normal": [
        "Deployment started at 3 PM UTC.",
        "Rollback plan is ready if issues arise.",
        "Deployment successful with zero downtime.",
        "Release v2.1.0 going out; monitoring dashboards.",
        "Staging validated; proceeding to production.",
        "Deploy complete; smoke tests passing.",
        "Release going out; rollback plan ready.",
        "Deployment in progress; ETA 15 minutes.",
        "Staging passed; promoting to prod.",
        "Build green; deploying to production.",
        "Release v2.2.0 rolling out; monitoring.",
        "Deploy started; notifications sent.",
        "Artifacts built; deploy in progress.",
        "Production deploy; canary first.",
        "Going live; support notified.",
        "Deployment window open; proceeding.",
        "Release complete; health checks running.",
        "Prod deploy in progress; watch the dashboards.",
        "Rollout started; zero-downtime expected.",
        "Deploy initiated; ETA 10 min."
      ],
      "chaos": [
        "Deploying to prod. See you on the other side.",
        "Pushed. Pray to the deploy gods.",
        "It's Friday. What could go wrong?",
        "Deploy in progress. Someone hold the pager.",
        "Merge to main. YOLO. I mean, we have a plan. Sort of.",
        "Shipping it. The runbook is a suggestion.",
        "Deploying. See you in the war room. Or the bar.",
        "Pushing to prod. The pager is charged. I'm not.",
        "It's 4 PM Friday. Deploy o'clock.",
        "Merge to main. We have rollback. We think.",
        "Shipping. Staging said yes. Staging is a liar.",
        "Deploy in progress. Someone order pizza.",
        "Going live. Hope you like green. Or red. We'll see.",
        "Pushing. The tests passed. The tests we have.",
        "Prod deploy. Documentation: forthcoming. Maybe.",
        "Shipping it. The canary will tell us. Or prod will.",
        "Deploy started. Coffee consumption: high.",
        "Merge complete. Monitoring: also complete. Hopefully.",
        "Going to prod. Rollback plan: we have one. Somewhere.",
        "Deploy initiated. Good luck to us all."
      ],
      "corporate": [
        "Release 2.3.1 has been promoted to production.",
        "Deployment window completed; post-release review scheduled.",
        "Change advisory approved; deployment executed per process.",
        "Release notes published; stakeholders notified.",
        "Production deployment successful; KPIs within tolerance.",
        "Go-live complete; support team briefed.",
        "Release 2.4.0 promoted; post-release review scheduled.",
        "Deployment executed per change advisory.",
        "Production release complete; KPIs monitored.",
        "Go-live successful; stakeholders notified.",
        "Release notes published; support briefed.",
        "Deployment window completed; no issues.",
        "Production promotion complete; audit trail updated.",
        "Release deployed; communication plan executed.",
        "Go-live successful; rollback criteria documented.",
        "Production release; post-implementation review scheduled.",
        "Deployment complete per governance.",
        "Release live; support runbook updated.",
        "Production deployment; stakeholder sign-off on file.",
        "Go-live complete; lessons learned scheduled."
      ],
      "devops": [
        "CI/CD pipeline completed; artifacts in registry.",
        "Canary rollout at 10%; monitoring metrics.",
        "Blue-green switch completed; old stack draining.",
        "ArgoCD sync complete; manifests applied.",
        "Terraform apply successful; infra updated.",
        "Deploy via GitOps; no manual intervention.",
        "Pipeline green; artifacts in registry; deploying.",
        "Canary at 10%; metrics look good; proceeding.",
        "Blue-green switch in progress; traffic shifting.",
        "ArgoCD sync done; manifests applied.",
        "Terraform apply complete; infra updated.",
        "Deploy automated; no manual steps.",
        "Rollout in progress; monitoring dashboards live.",
        "Feature flags set; gradual rollout started.",
        "Deploy complete; runbook followed. For once.",
        "Artifacts promoted; production updated.",
        "CI/CD pipeline finished; deploy in progress.",
        "Rollback path tested; deploying.",
        "Observability in place; deploying.",
        "SLO headroom checked; good to deploy."
      ],
      "sarcastic": [
        "Deployed. The staging environment that we don't have.",
        "Ship it. The tests passed. The tests we wrote.",
        "Production updated. Hope you like surprises.",
        "Deploy successful. Customer impact: TBD.",
        "We're live. The monitoring is also live. Coincidence?",
        "Shipped. Documentation to follow. Eventually.",
        "Deployed. To production. The one we use. For real.",
        "Ship it. The tests passed. We wrote the tests.",
        "Production updated. Customer impact: we'll find out.",
        "We're live. Monitoring is also live. What a coincidence.",
        "Shipped. The staging env was representative. Sure.",
        "Deploy successful. Runbook: we'll update. Eventually.",
        "Production updated. Hope the canary survives.",
        "Shipped. The pipeline said green. The pipeline is generous.",
        "Deploy complete. Documentation: in our hearts.",
        "We're live. Rollback plan: in the runbook. Somewhere.",
        "Shipped. Feature flags: we have them. We used one.",
        "Deploy done. Postmortem: only if something breaks. So, probably.",
        "Production updated. Tests passed. Staging passed. Prod: TBD.",
        "Shipped. Good luck to the on-call. It's not me. Tonight."
      ]
    }
  },
  "excuse": {
    "name": "excuse",
    "description": "Common excuses for missing deadlines or meetings",
    "modes": [
      "normal",
      "chaos",
      "sarcastic",
      "corporate",
      "toxic"
    ],
    "examples": [
      "I was stuck in traffic.",
      "My internet was down."
    ],
    "examplesByMode": {
      "normal": [
        "I was stuck in traffic.",
        "My internet was down.",
        "I had a family emergency.",
        "Calendar conflict I didn't see.",
        "Meeting ran over; couldn't make it.",
        "Got pulled into an urgent production issue.",
        "VPN dropped right before the call.",
        "Had a last-minute customer escalation.",
        "Laptop battery died mid-meeting.",
        "Another meeting ran over; couldn't make it.",
        "Doctor's appointment ran late.",
        "Childcare fell through at the last minute.",
        "Flight delay; still in transit.",
        "Power outage at home.",
        "Critical bug in prod; had to jump in.",
        "Calendar didn't sync; missed the invite.",
        "Double-booked by mistake; chose the other one.",
        "Car trouble this morning.",
        "Internet outage in my area.",
        "Unexpected interview conflict; had to prioritize."
      ],
      "chaos": [
        "A squirrel ate through the fiber line.",
        "My laptop decided to install updates during the call.",
        "The cat sat on the keyboard and closed everything.",
        "A bird flew into the power substation. Seriously.",
        "My keyboard developed a mind of its own.",
        "The WiFi is haunted. I have evidence.",
        "A meteor hit the data center. Local one.",
        "My chair decided to recline. Aggressively. During the call.",
        "The dog ate my Ethernet cable. Again.",
        "Time zone shifted. I didn't get the memo.",
        "My mic became sentient. It said no.",
        "The building's WiFi is in a mood. I have witnesses.",
        "A parade blocked the street. For 4 hours.",
        "My coffee machine staged a coup. I had to negotiate.",
        "The cloud was literal. Fog. Couldn't see the screen.",
        "My keyboard learned a new language. It's not English.",
        "The VPN thought I was in 2030. Time travel is messy.",
        "A gremlin unplugged the router. I'm not even kidding.",
        "The sun was in my eyes. I work in a basement.",
        "My chair wheels went on strike. Solidarity."
      ],
      "sarcastic": [
        "I was busy aligning synergies.",
        "My calendar had a conflict with reality.",
        "I thought it was optional. Like sleep.",
        "I had a conflict with my other meeting about this meeting.",
        "I was in a meeting about reducing meetings.",
        "My OOO said I was out. I was in. The OOO lied.",
        "I was optimizing my calendar. It's self-care.",
        "I had a conflict with my conflict resolution meeting.",
        "I was in a working session. Working. On my sanity.",
        "The invite said optional. I opted. Out.",
        "I was reducing meeting load. By not attending. Meta.",
        "I had a 1:1 with my to-do list. It was urgent.",
        "I was in a meeting about the meeting we're having now.",
        "My calendar had a nervous breakdown. I'm supporting it.",
        "I was aligning with my priorities. They said skip it.",
        "I had a conflict with my focus time. Focus won.",
        "The meeting moved. I didn't. We're both right.",
        "I was in a deep work block. The deepest.",
        "I had a prior commitment to my inbox. It's demanding.",
        "I was in a sync. With myself. It ran over."
      ],
      "corporate": [
        "I had a conflicting stakeholder engagement.",
        "Prior commitment to another initiative.",
        "My calendar sync had a delay.",
        "I was in back-to-backs; couldn't transition in time.",
        "Double-booked; prioritizing per the RACI.",
        "Resource allocation conflict; escalating.",
        "Conflicting stakeholder engagement; had to prioritize.",
        "Prior commitment to another program; couldn't move.",
        "Calendar sync delay; invite arrived after the meeting.",
        "Back-to-back commitments; no transition time.",
        "Double-booked per RACI; higher-priority meeting won.",
        "Initiative overlap; had to choose one.",
        "Governance meeting took precedence.",
        "Board prep conflicted; exec commitment.",
        "Cross-functional sync had priority.",
        "Compliance training overlapped; mandatory.",
        "Vendor call ran over; couldn't leave.",
        "Program review was scheduled first.",
        "Stakeholder alignment meeting took priority."
      ],
      "toxic": [
        "Didn't think my presence was required.",
        "That meeting could've been an email. So I treated it like one.",
        "I had more important things to do.",
        "You didn't send a calendar invite. My fault?",
        "I prioritize deliverables over meetings.",
        "Sorry, I block 2–4 for deep work. Your meeting lost.",
        "Didn't think my presence was required. Still don't.",
        "I had more important things to do. I still do.",
        "I prioritize deliverables over meetings. Consistently.",
        "Deep work block. Your meeting didn't make the cut.",
        "I don't do meetings before 10. Or after 3. Or during lunch.",
        "That could've been a Slack. It still can be.",
        "I was heads-down. Still am. By design.",
        "My calendar is full. Of things that matter. To me.",
        "I block focus time. Your meeting was not in the block.",
        "I prioritize. You didn't make the list. Sorry not sorry.",
        "That meeting had no agenda. So I had no attendance.",
        "I was delivering. You were meeting. Different priorities."
      ]
    }
  },
  "incident": {
    "name": "incident",
    "description": "Incident reports and updates",
    "modes": [
      "normal",
      "chaos",
      "corporate",
      "security",
      "devops",
      "sarcastic"
    ],
    "examples": [
      "Incident #1234 is being investigated.",
      "Root cause analysis in progress."
    ],
    "examplesByMode": {
      "normal": [
        "Incident #1234 is being investigated.",
        "Root cause analysis in progress.",
        "Incident resolved, system fully operational.",
        "Mitigation applied; monitoring for recurrence.",
        "Post-incident review scheduled for tomorrow.",
        "Impact: partial outage, 15 min; users notified.",
        "Incident detected; team investigating.",
        "Mitigation in progress; ETA 20 minutes.",
        "Service restored; monitoring for stability.",
        "Post-incident review scheduled for Friday.",
        "Root cause identified; fix in progress.",
        "Users notified; status page updated.",
        "Incident severity: P2; on-call engaged.",
        "Workaround deployed; permanent fix planned.",
        "Incident resolved; no further impact expected.",
        "RCA scheduled; follow-up tasks created.",
        "Impact: limited to specific region; resolved.",
        "Incident closed; runbook updated.",
        "All systems operational; incident complete.",
        "Lessons learned doc in progress."
      ],
      "chaos": [
        "Everything is on fire. We're on it. Maybe.",
        "Incident declared. Caffeine levels critical.",
        "We have no idea yet. Stand by.",
        "War room assembled. So is the panic.",
        "Investigating. The logs are not helpful. Send help.",
        "Incident in progress. Morale: also in progress.",
        "Incident: ongoing. Clarity: not so much.",
        "We're investigating. The system is not cooperating.",
        "War room: active. Answers: pending.",
        "Incident in progress. The runbook is silent. We're not.",
        "We're on it. We don't know what it is yet. But we're on it.",
        "Stand by. We're standing by. So is the pager.",
        "Incident declared. Coffee: ordered. Resolution: TBD.",
        "Investigating. The error message is unhelpful. Very.",
        "Morale: in progress. Incident: also in progress. We're trying."
      ],
      "corporate": [
        "A major incident has been declared; war room convened.",
        "Post-incident review scheduled within 48 hours.",
        "Stakeholders have been notified per comms plan.",
        "Business impact assessment in progress.",
        "Incident timeline being documented for RCA.",
        "Escalation path activated; exec sponsor informed.",
        "Exec sponsor informed; escalation path active.",
        "War room convened; updates every 30 min.",
        "Stakeholder communication in progress.",
        "Business continuity team engaged.",
        "RCA timeline communicated; report to follow.",
        "Governance followed; incident logged.",
        "Program impact assessed; exec update scheduled.",
        "Post-incident review scheduled; lessons learned to follow.",
        "Incident closed; stakeholder summary sent."
      ],
      "security": [
        "Potential security incident under investigation.",
        "Containment in progress; no data exfil detected.",
        "Security incident closed; remediation and hardening completed.",
        "Credential rotation initiated; scope assessed.",
        "IDS triggered; investigating; no confirmed breach.",
        "Security incident declared; IR team engaged.",
        "IR team engaged; containment ongoing.",
        "Security review in progress; impact TBD.",
        "No data exfil detected; monitoring.",
        "Remediation and hardening completed.",
        "Security incident resolved; audit trail updated.",
        "Vulnerability contained; patch in progress.",
        "Access reviewed; least-privilege confirmed.",
        "Security incident closed; report to follow.",
        "IR complete; no further action required."
      ],
      "devops": [
        "Pager fired; on-call investigating.",
        "Rollback in progress; monitoring error rates.",
        "Incident resolved; runbook updated.",
        "SLO breach; error budget consumed; RCA inbound.",
        "Service degraded; canary rollback executing.",
        "Incident closed; follow-up tasks in backlog.",
        "On-call engaged; mitigation in progress.",
        "Rollback complete; stability restored.",
        "Incident resolved; postmortem scheduled.",
        "SLO recovering; error rate dropping.",
        "Service restored; monitoring confirmed.",
        "Incident ticket updated; resolution documented.",
        "Runbook followed; incident closed.",
        "Follow-up tasks created; on-call relieved."
      ],
      "sarcastic": [
        "Incident: ongoing. Confidence: low. Coffee: high.",
        "We've identified the problem: it's everything.",
        "RCA complete. Blame: legacy. Solution: rewrite. Timeline: never.",
        "Incident resolved. Root cause: Friday afternoon deploy.",
        "Post-mortem finding: we knew this would happen. We did it anyway.",
        "Incident report: it broke. We fixed it. Don't ask how.",
        "Root cause: we touched it. Don't touch things.",
        "Incident resolved. How? Magic. And rollback.",
        "RCA finding: the system is complicated. We're complicated. It's fine.",
        "Postmortem: we'll do better. We said that last time.",
        "Incident: resolved. Confidence: medium. Hope: high.",
        "We fixed it. The fix might need a fix. We'll see.",
        "Incident closed. Lessons learned: we have a list. A long list.",
        "Resolution: we reverted. The revert worked. This time."
      ]
    }
  },
  "lgtm": {
    "name": "lgtm",
    "description": "LGTM (Looks Good To Me) approvals",
    "modes": [
      "normal",
      "sarcastic",
      "devops",
      "chaos",
      "corporate"
    ],
    "examples": [
      "LGTM! Ready to merge.",
      "Code looks good, approved."
    ],
    "examplesByMode": {
      "normal": [
        "LGTM! Ready to merge.",
        "Code looks good, approved.",
        "No issues found, LGTM.",
        "Nice work, ship it!",
        "Approved. Clean implementation.",
        "LGTM — tests pass, logic checks out.",
        "LGTM. Merge when ready.",
        "Approved. No nits from me.",
        "Looks good to me. Go for it.",
        "LGTM. Clean and readable.",
        "Approved. Ready for main.",
        "LGTM. Good changes.",
        "Ship it when the pipeline is green.",
        "Approved. Tests and style look good.",
        "LGTM. No blockers here.",
        "Approved. Nice work."
      ],
      "sarcastic": [
        "LGTM. I didn't read it but the CI is green.",
        "Ship it. What could possibly go wrong?",
        "LGTM. My lawyer says I can't say more.",
        "Approved. I trust you. Mostly. Kind of.",
        "LGTM. The linter didn't complain. Good enough.",
        "Looks good. I skimmed the last 3 lines. We're fine.",
        "LGTM. I read the title. That counts.",
        "Approved. The bots said yes. I'm with the bots.",
        "LGTM. My approval is as thorough as the average PR description.",
        "Ship it. I'll blame the tests if it breaks.",
        "Approved. I have meetings in 5. This is fine.",
        "LGTM. No one else reviewed it either. Solidarity.",
        "Looks good. I'm approving so I can close the tab.",
        "LGTM. The diff was long. I trusted the summary.",
        "Approved. If prod breaks we'll have a fun retro.",
        "LGTM. I nodded. That's basically a review."
      ],
      "devops": [
        "LGTM. Pipeline green, coverage acceptable.",
        "Approved. Merge when checks pass.",
        "LGTM; deploy to staging first per process.",
        "Approved. Infra changes look safe.",
        "LGTM. Monitoring and alerts in place.",
        "Approved. Runbook updated. Good to go.",
        "LGTM. Canary plan looks solid.",
        "Approved. Rollback path documented.",
        "LGTM. SLO impact assessed; acceptable.",
        "Approved. Feature flags in place.",
        "LGTM. No new critical alerts introduced.",
        "Approved. Deploy during window only.",
        "LGTM. Infra as code changes validated.",
        "Approved. Observability hooks present.",
        "LGTM. Dependency bumps look safe.",
        "Approved. Good to merge after final checks."
      ],
      "chaos": [
        "LGTM. If it breaks prod, we didn't have this conversation.",
        "Ship it. YOLO. I mean, we have rollback. Right?",
        "Approved. Hope the staging env was real.",
        "LGTM. Friday deploy. No fear. All fear.",
        "Looks good. I'm on PTO next week. Good luck.",
        "Approved. The tests passed. The tests we have.",
        "LGTM. Staging was green. Staging is always green.",
        "Ship it. The pager is someone else's problem. Tonight.",
        "Approved. I didn't run it locally. Neither did you.",
        "LGTM. Merge and pray. Standard process.",
        "Looks good. Our rollback is only two steps. Step one: cry.",
        "Approved. Hope the canary doesn't get eaten.",
        "LGTM. We'll fix it in prod. We always do.",
        "Ship it. The deploy gods are feeling generous. Maybe.",
        "Approved. Documentation: we'll add it later.",
        "LGTM. If it's broken we'll find out. Together."
      ],
      "corporate": [
        "LGTM. Change advisory submitted.",
        "Approved per code review standards.",
        "LGTM. Compliance check passed.",
        "Approved. Release notes updated.",
        "LGTM. Stakeholder sign-off documented.",
        "Approved. Ready for deployment window.",
        "LGTM. Governance checklist complete.",
        "Approved per change management policy.",
        "LGTM. Risk assessment on file.",
        "Approved. Communication plan executed.",
        "LGTM. Post-release review scheduled.",
        "Approved. Audit trail updated.",
        "LGTM. Escalation path confirmed.",
        "Approved. Rollback criteria documented.",
        "LGTM. Stakeholder notification sent.",
        "Approved. Ready for production promotion."
      ]
    }
  },
  "maybe": {
    "name": "maybe",
    "description": "Uncertain or tentative responses",
    "modes": [
      "normal",
      "corporate",
      "chaos",
      "sarcastic"
    ],
    "examples": [
      "Maybe, let's discuss further.",
      "Possibly, needs more info."
    ],
    "examplesByMode": {
      "normal": [
        "Maybe, let's discuss further.",
        "Possibly, needs more info.",
        "Not sure yet, will update soon.",
        "Unclear — need to validate with the team.",
        "Could work; need to confirm dependencies.",
        "Tentative yes, pending a few checks."
      ],
      "corporate": [
        "Subject to stakeholder alignment.",
        "Contingent upon resource availability.",
        "Pending approval from the appropriate level.",
        "Under consideration; decision timeline TBD.",
        "Requires further analysis before commitment.",
        "Provisional; formal approval in progress."
      ],
      "chaos": [
        "Maybe. Our production environment said maybe too.",
        "Possibly. The runbook is unclear. Very unclear.",
        "Not sure. The person who knew left last week.",
        "Could be. We're still finding out what we built.",
        "Maybe yes, maybe no. The logs are inconclusive.",
        "Tentative. Everything is tentative. Always."
      ],
      "sarcastic": [
        "Maybe. Like maybe I'll check my email. Eventually.",
        "Possibly. If the planets align and we get budget.",
        "Not sure. Let me circle back after my 47 meetings.",
        "Could work. In theory. Theory and practice differ.",
        "Maybe. I'll add it to the backlog. Of maybes.",
        "Tentative yes. The most committed answer I have."
      ]
    }
  },
  "meeting": {
    "name": "meeting",
    "description": "Meeting notes or reminders",
    "modes": [
      "normal",
      "corporate",
      "devops",
      "chaos",
      "sarcastic"
    ],
    "examples": [
      "Don't forget the daily standup at 10 AM.",
      "Please prepare your updates before the meeting."
    ],
    "examplesByMode": {
      "normal": [
        "Don't forget the daily standup at 10 AM.",
        "Please prepare your updates before the meeting.",
        "Meeting agenda: project status and blockers.",
        "Retro at 2 PM — bring your wins and learnings.",
        "Sprint planning starts at 9; backlog prioritized.",
        "Demo at 4 PM — stakeholders invited."
      ],
      "corporate": [
        "Q3 planning sync is on the calendar; pre-reads required.",
        "Stakeholder review scheduled; deck to be shared 24h prior.",
        "All-hands reminder: please submit questions in advance.",
        "Board prep meeting; exec summary due by EOD.",
        "Cross-functional alignment; RACI to be finalized.",
        "Quarterly business review; KPIs and roadmap on deck."
      ],
      "devops": [
        "Incident retro at 2 PM; join if you were in the war room.",
        "SRE sync: focus on SLOs and error budget.",
        "Release review at 4 PM; deploy owners expected.",
        "On-call handoff at 9 AM; runbooks updated.",
        "Infra review: capacity planning and scaling.",
        "Postmortem for INC-420; blameless. Mostly."
      ],
      "chaos": [
        "Meeting at 3. No agenda. No idea what we're discussing.",
        "Standup: tell us what's on fire. Literally.",
        "Retro: what went wrong. Everything. Everything went wrong.",
        "Planning: we're planning to have a plan. Eventually.",
        "Sync meeting: we'll sync on why we need fewer syncs.",
        "All-hands: bring snacks. And hope."
      ],
      "sarcastic": [
        "Meeting that could've been an email: 2 PM.",
        "Standup: 15 minutes of updates no one will remember.",
        "Planning poker: we're all voting 13. Every time.",
        "Retro: glad we're blameless. The process isn't.",
        "Demo: featuring the thing that almost shipped.",
        "Sync: to sync on our lack of sync. Very meta."
      ]
    }
  },
  "motivate": {
    "name": "motivate",
    "description": "Motivational quotes and phrases",
    "modes": [
      "normal",
      "wholesome",
      "toxic",
      "chaos",
      "sarcastic"
    ],
    "examples": [
      "Keep pushing forward!",
      "Every day is a new opportunity."
    ],
    "examplesByMode": {
      "normal": [
        "Keep pushing forward!",
        "Every day is a new opportunity.",
        "Success is not final; failure is not fatal.",
        "You've got this. One deploy at a time.",
        "Progress over perfection.",
        "Celebrate the small wins."
      ],
      "wholesome": [
        "You've got this. One step at a time.",
        "It's okay to take a breath. Then try again.",
        "Progress over perfection. You're doing great.",
        "Your worth isn't measured by your sprint velocity.",
        "Take care of yourself. The code can wait.",
        "You're doing better than you think."
      ],
      "toxic": [
        "Sleep is for the weak. Deploy at 2 AM.",
        "If you're not stressed, you're not shipping.",
        "Another day, another incident. Embrace it.",
        "Hustle culture: because burnout is a badge of honor.",
        "Vacation? What's that? We have prod.",
        "The grind doesn't stop. Neither should you. Apparently."
      ],
      "chaos": [
        "You're one deploy away from glory. Or disaster. Both?",
        "Today might be the day everything works. Might.",
        "Keep going. The pager will find you anyway.",
        "Optimism: production might not crash. Today.",
        "You got this. Probably. We believe in you. Maybe.",
        "One more PR. What's the worst that could happen?"
      ],
      "sarcastic": [
        "Rise and grind. Or rise and groan. Same energy.",
        "Another day, another dollar. Mostly in AWS costs.",
        "You're one meeting away from greatness. Or insanity.",
        "Hustle! Just kidding. Take a break. Please.",
        "Dream big. Or just dream of a green pipeline.",
        "Seize the day. Or the deploy button. Whichever."
      ]
    }
  },
  "no": {
    "name": "no",
    "description": "Negative responses",
    "modes": [
      "normal",
      "corporate",
      "chaos",
      "sarcastic",
      "security"
    ],
    "examples": [
      "No, that won't work.",
      "I don't think that's feasible."
    ],
    "examplesByMode": {
      "normal": [
        "No, that won't work.",
        "I don't think that's feasible.",
        "Negative, please reconsider.",
        "Not at this time.",
        "We'll need to pass on that.",
        "Doesn't align with current priorities."
      ],
      "corporate": [
        "Out of scope for this quarter.",
        "Requires additional stakeholder approval.",
        "Not aligned with strategic objectives.",
        "Resource constraints prevent this at present.",
        "We'll need to escalate for consideration.",
        "Outside the agreed RACI boundaries."
      ],
      "chaos": [
        "No. Our production said no first.",
        "Absolutely not. We tried. We're still recovering.",
        "No. The last time we did that, we had an incident.",
        "Hard no. The runbook doesn't cover that. Nothing does.",
        "No. I don't have a good reason. Just no.",
        "Negative. The system has spoken. It's upset."
      ],
      "sarcastic": [
        "No. But thanks for the confidence.",
        "Sure, no. Same thing, right?",
        "No. I'd explain but I have 47 meetings.",
        "Negative. I've seen what happens. We all have.",
        "No. My calendar says maybe. My soul says no.",
        "Pass. We have enough incidents. Thank you."
      ],
      "security": [
        "Denied. Violates least-privilege policy.",
        "No. That would require prod access. Hard no.",
        "Security review says no. We listen to security.",
        "Blocked. Credentials in plaintext? No.",
        "Access denied. And logged. Always logged.",
        "Negative. That config would open a hole. A big one."
      ]
    }
  },
  "policy": {
    "name": "policy",
    "description": "Company policy statements",
    "modes": [
      "normal",
      "corporate",
      "security",
      "chaos",
      "sarcastic"
    ],
    "examples": [
      "Remote work is allowed up to 3 days a week.",
      "Code reviews must be done before merging."
    ],
    "examplesByMode": {
      "normal": [
        "Remote work is allowed up to 3 days a week.",
        "Code reviews must be done before merging.",
        "Use strong passwords and enable MFA.",
        "PTO requests require 2 weeks notice.",
        "Production changes need approval.",
        "Documentation required for all APIs."
      ],
      "corporate": [
        "All remote work must comply with the flexible work policy.",
        "Merges require approval per the code review standard.",
        "Access and authentication follow the identity policy.",
        "PTO accrual and usage per the handbook.",
        "Change management process applies to production.",
        "Knowledge base must be updated for all changes."
      ],
      "security": [
        "Production access requires MFA and justification.",
        "Secrets must be stored in the vault; no env vars.",
        "Patching SLA is 7 days for critical CVEs.",
        "No production credentials in chat or email.",
        "Least-privilege access; request what you need.",
        "Security review required for third-party integrations."
      ],
      "chaos": [
        "Policy: we have one. It's in Confluence. Page 47.",
        "Remote work: yes. From anywhere. Even the war room.",
        "Code review: someone glances at it. Usually. Policy met.",
        "MFA: required. Except when it's not. Don't ask.",
        "Documentation: we document our lack of documentation.",
        "Policy compliance: it's the spirit that counts. Right?"
      ],
      "sarcastic": [
        "We have policies. We also have exceptions. Many exceptions.",
        "Policy: read it. Follow it. Or don't. We're flexible.",
        "The policy says one thing. Reality says another. Both are true.",
        "Policies are guidelines. Strong guidelines. Very strong.",
        "Compliance: we're 80% there. The 80% we remember.",
        "Policy handbook: 200 pages. Key points: 3. Good luck."
      ]
    }
  },
  "random": {
    "name": "random",
    "description": "Return a random response from any endpoint",
    "modes": [
      "normal"
    ],
    "examples": [
      "(random)"
    ],
    "examplesByMode": {
      "normal": [
        "(random)"
      ]
    }
  },
  "realitycheck": {
    "name": "realitycheck",
    "description": "Reality check statements to ground the team",
    "modes": [
      "normal",
      "corporate",
      "sarcastic",
      "chaos",
      "devops"
    ],
    "examples": [
      "Remember, deadlines are firm.",
      "We have limited resources, plan accordingly."
    ],
    "examplesByMode": {
      "normal": [
        "Remember, deadlines are firm.",
        "We have limited resources, plan accordingly.",
        "Quality is more important than speed.",
        "Scope creep has consequences. Plan for it.",
        "Technical debt compounds. Address it.",
        "We can't do everything. Prioritize ruthlessly."
      ],
      "corporate": [
        "Scope and timeline are fixed; adjust scope or extend timeline.",
        "Resource allocation is constrained; prioritize accordingly.",
        "We are accountable to the committed delivery date.",
        "Stakeholder expectations are set; manage them.",
        "Budget is allocated; no additional headcount this quarter.",
        "Committed dates are tracked at the program level."
      ],
      "sarcastic": [
        "Sure, we can do that. And I can grow wings.",
        "The deadline is when it is. Physics doesn't care.",
        "We have two options: do it right or do it twice.",
        "Adding scope doesn't add time. It never has.",
        "The roadmap is full. Of hopes. And dreams. Not capacity.",
        "Reality: we have 2 devs. Ask: can 2 devs do 10 things? No."
      ],
      "chaos": [
        "Reality check: prod is still on fire from last week.",
        "We have 3 hours. The scope says 3 weeks. Adjust expectations.",
        "The runbook is outdated. So is our understanding.",
        "Reality: we're one incident away from a very long weekend.",
        "Capacity check: we're at 147%. Of something. Not good.",
        "Ground truth: the docs lie. The logs lie. We're winging it."
      ],
      "devops": [
        "Error budget is exhausted. No more risky deploys.",
        "SLO breach means we pause feature work. Period.",
        "Incident count is up. Quality gates need tightening.",
        "Tech debt is blocking. It's not optional anymore.",
        "On-call fatigue is real. Rotation needs rebalancing.",
        "Reality: we're at 90% capacity. Stop saying yes."
      ]
    }
  },
  "risk": {
    "name": "risk",
    "description": "Risk assessment statements",
    "modes": [
      "normal",
      "corporate",
      "security",
      "chaos",
      "sarcastic"
    ],
    "examples": [
      "High risk of delay due to dependencies.",
      "Potential security vulnerabilities detected."
    ],
    "examplesByMode": {
      "normal": [
        "High risk of delay due to dependencies.",
        "Potential security vulnerabilities detected.",
        "Resource constraints may impact delivery.",
        "Single point of failure in the architecture.",
        "Vendor lock-in risk if we proceed.",
        "Technical debt increasing; sustainability at risk."
      ],
      "corporate": [
        "Risk register updated; mitigation owners assigned.",
        "Delivery risk is elevated; escalation path documented.",
        "Dependency risk has been flagged to program.",
        "Risk accepted with compensating controls; documented.",
        "Residual risk within tolerance; proceeding.",
        "Risk assessment completed; RACI for mitigation."
      ],
      "security": [
        "Critical risk: unpatched dependency in the supply chain.",
        "Risk accepted with compensating controls; documented.",
        "Security assessment identified medium residual risk.",
        "Credential exposure risk; rotation required.",
        "Data classification risk; encryption gap identified.",
        "Third-party risk: vendor security posture under review."
      ],
      "chaos": [
        "Risk: high. Mitigation: hope. We're hopeful.",
        "Everything is a risk. We've normalized it.",
        "Risk register: we have one. We don't look at it.",
        "Single point of failure: me. I'm the SPOF. Send help.",
        "Risk assessment: we'll do it post-incident. Classic.",
        "Risk level: yes. Specifics: also yes. All of them."
      ],
      "sarcastic": [
        "Risk: low. Our definition of low is flexible.",
        "We've accepted the risk. We didn't have a choice.",
        "Risk mitigation: we have a plan. It's optimistic.",
        "Residual risk: acceptable. To whom? Unclear.",
        "Risk register updated. With more risks. Progress?",
        "Risk assessment: do we want to know? No. Documented anyway."
      ]
    }
  },
  "roadmap": {
    "name": "roadmap",
    "description": "Roadmap updates and priorities",
    "modes": [
      "normal",
      "corporate",
      "chaos",
      "sarcastic",
      "devops"
    ],
    "examples": [
      "Next milestone: feature complete by end of month.",
      "Focus on bug fixes in sprint 5."
    ],
    "examplesByMode": {
      "normal": [
        "Next milestone: feature complete by end of month.",
        "Focus on bug fixes in sprint 5.",
        "Planning for Q3 initiatives underway.",
        "MVP scope locked; iterating from feedback.",
        "Tech debt sprint scheduled for next month.",
        "Roadmap review: bi-weekly with stakeholders."
      ],
      "corporate": [
        "Roadmap has been updated; Q3 priorities are locked.",
        "Strategic initiatives are reflected in the product roadmap.",
        "Stakeholders have visibility into the next two quarters.",
        "OKR alignment complete; roadmap reflects key results.",
        "Investment areas prioritized per board guidance.",
        "Portfolio roadmap published; dependencies mapped."
      ],
      "chaos": [
        "Roadmap: we have one. It changes. Often. Daily.",
        "Priorities: everything. Everything is priority.",
        "Q3 plan: survive. That's the plan.",
        "Roadmap updated. Again. This is the 12th version this week.",
        "Strategic direction: forward. Mostly. We think.",
        "Milestones: aspirational. Very aspirational."
      ],
      "sarcastic": [
        "Roadmap: comprehensive. Accurate: debatable.",
        "Priorities set. By someone. Somewhere. We're executing.",
        "The roadmap says Q3. Reality says Q4. Or Q1. TBD.",
        "Strategic pillars: we have four. They're all urgent.",
        "Roadmap visibility: 100%. Confidence: 47%.",
        "We're agile. The roadmap is a suggestion. A strong suggestion."
      ],
      "devops": [
        "SLO focus next quarter; reliability over features.",
        "Platform maturity roadmap: observability first.",
        "Tech debt sprint; 20% capacity for infrastructure.",
        "Migration roadmap: legacy to cloud. 18 months. Optimistic.",
        "Automation initiative: reduce toil by 30%.",
        "On-call improvements; runbook and alert refinement."
      ]
    }
  },
  "rollback": {
    "name": "rollback",
    "description": "Rollback instructions and alerts",
    "modes": [
      "normal",
      "chaos",
      "corporate",
      "devops",
      "sarcastic"
    ],
    "examples": [
      "Rollback initiated due to critical bug.",
      "Previous stable version restored."
    ],
    "examplesByMode": {
      "normal": [
        "Rollback initiated due to critical bug.",
        "Previous stable version restored.",
        "Rollback completed successfully.",
        "Reverting to last known good release.",
        "Rollback in progress; ETA 10 minutes.",
        "Traffic shifted back; monitoring for stability."
      ],
      "chaos": [
        "Rolling back. Again. Hold my coffee.",
        "We're going back. No one say 'I told you so.'",
        "Rollback in progress. Someone check the runbook.",
        "Reverting. The rollback might need a rollback.",
        "Going back in time. Wish us luck.",
        "Rollback initiated. Morale: also rolling back."
      ],
      "corporate": [
        "A rollback has been executed per the change process.",
        "Previous known-good release has been restored.",
        "Post-rollback review will be scheduled within 48 hours.",
        "Rollback completed; stakeholders notified.",
        "Change reversal documented; RCA to follow.",
        "Service restored to pre-incident state; impact logged."
      ],
      "devops": [
        "Rollback triggered; traffic shifting to previous version.",
        "Canary rollback complete; monitoring stable.",
        "Rollback successful; incident ticket updated.",
        "ArgoCD revert applied; previous manifest active.",
        "Blue-green switch reverted; old stack receiving traffic.",
        "Rollback complete; pipeline artifacts retained for analysis."
      ],
      "sarcastic": [
        "Rollback: the feature we use most often.",
        "We've rolled back. The rollback. Rollback-ception.",
        "Previous version restored. It had bugs too. Different bugs.",
        "Rollback successful. Confidence: medium. Hope: high.",
        "We're back. To the version that caused the last rollback.",
        "Rollback complete. Documenting lessons learned. Again."
      ]
    }
  },
  "standup": {
    "name": "standup",
    "description": "Daily standup prompts and notes",
    "modes": [
      "normal",
      "corporate",
      "devops",
      "chaos",
      "sarcastic"
    ],
    "examples": [
      "What did you do yesterday?",
      "What will you do today?"
    ],
    "examplesByMode": {
      "normal": [
        "What did you do yesterday?",
        "What will you do today?",
        "Any blockers or issues?",
        "Progress on the current sprint?",
        "Anything need escalation?",
        "Wins and learnings from the week?"
      ],
      "corporate": [
        "Please share progress against your committed objectives.",
        "Highlight any risks or dependencies for the program.",
        "Updates should be concise; details in the tracker.",
        "Status against the sprint goals?",
        "Any cross-functional blockers to raise?",
        "Key accomplishments and priorities for today."
      ],
      "devops": [
        "What shipped? What's on fire? What's next?",
        "Any incidents or near-misses to call out?",
        "SLO status and error budget for the week?",
        "On-call handoff: anything to know?",
        "Deployments planned? Rollbacks in progress?",
        "Platform health: any anomalies or tech debt wins?"
      ],
      "chaos": [
        "What broke? What's still broken? What will break?",
        "Any incidents? All of them? Okay, highlights.",
        "Status: surviving. Blockers: existence. Next: hope.",
        "What did you do? Put out fires. Will do? More fires.",
        "SLO: we have one? Error budget: negative? Great.",
        "Standup in 30 seconds: things are bad. Questions?"
      ],
      "sarcastic": [
        "Yesterday: meetings. Today: meetings. Blockers: meetings.",
        "Progress: I showed up. That counts. Right?",
        "Status: the same as yesterday. And the day before.",
        "What I did: context switched. What I'll do: context switch.",
        "Blockers: the sprint. The scope. Reality.",
        "Updates: we're agile. Very agile. Constantly pivoting."
      ]
    }
  },
  "thisisfine": {
    "name": "thisisfine",
    "description": "Humorous 'this is fine' style messages",
    "modes": [
      "normal",
      "chaos",
      "sarcastic",
      "corporate",
      "devops"
    ],
    "examples": [
      "Everything is on fire but this is fine.",
      "Keep calm and carry on."
    ],
    "examplesByMode": {
      "normal": [
        "Everything is on fire but this is fine.",
        "Keep calm and carry on.",
        "Ignoring problems won't make them go away.",
        "This is fine. We're fine. Probably.",
        "Smile through the chaos.",
        "Optimism: the dashboard is red but our spirits are high."
      ],
      "chaos": [
        "The dashboard is red. I'm choosing to see it as festive.",
        "Yes, prod is down. No, I'm not panicking. Much.",
        "This is fine. We're fine. Everything is fine.",
        "The alerts are screaming. I'm choosing to hear music.",
        "Five simultaneous incidents. This is fine. Totally fine.",
        "The runbook doesn't cover this. We're improvising. It's fine."
      ],
      "sarcastic": [
        "Clearly this is a feature, not a bug.",
        "We'll fix it in the next sprint. So never.",
        "I've decided to be optimistic. The bar is low.",
        "This is fine. My therapist says denial is a strategy.",
        "Everything's under control. Control is a spectrum.",
        "Fine is relative. We're relatively fine. Ish."
      ],
      "corporate": [
        "We're experiencing expected variance. This is fine.",
        "Stakeholders have been notified. We're fine.",
        "The incident is contained. To the entire system. Fine.",
        "Post-incident review scheduled. All fine.",
        "Business continuity maintained. Sort of. Fine.",
        "We have a plan. The plan is to remain calm. Fine."
      ],
      "devops": [
        "Error rate: 47%. This is fine. We're fine.",
        "Pager went off. Again. This is fine.",
        "Rollback in progress. For the third time. Fine.",
        "SLO: breached. Error budget: negative. This is fine.",
        "On-call for 72 hours. This is fine. Send coffee.",
        "The pipeline is red. The pipeline is always red. Fine."
      ]
    }
  },
  "yes": {
    "name": "yes",
    "description": "Affirmative responses",
    "modes": [
      "normal",
      "corporate",
      "chaos",
      "sarcastic",
      "devops"
    ],
    "examples": [
      "Yes, let's proceed.",
      "Absolutely, good idea."
    ],
    "examplesByMode": {
      "normal": [
        "Yes, let's proceed.",
        "Absolutely, good idea.",
        "Confirmed, moving forward.",
        "Approved. Go ahead.",
        "Sounds good. Proceed.",
        "Affirmative. Let's do it."
      ],
      "corporate": [
        "Approved per governance process.",
        "Stakeholder sign-off received. Proceed.",
        "Within scope; authorized to proceed.",
        "Compliance confirmed. Green light.",
        "Resource allocation approved. Execute.",
        "Change advisory approved. Proceed as planned."
      ],
      "chaos": [
        "Yes. We'll regret this. But yes.",
        "Absolutely. What's the worst that could happen?",
        "Confirmed. Hope the rollback works.",
        "Yes. Sending prayers to the deploy gods.",
        "Proceed. I'll be in the war room. Emotionally.",
        "Affirmative. The pager is charged. I'm not."
      ],
      "sarcastic": [
        "Yes. I have concerns. But yes.",
        "Absolutely. It's not like we have a choice.",
        "Confirmed. My calendar already said yes. I'm just catching up.",
        "Approved. The backlog said so. Who am I to argue?",
        "Sounds good. I'll document my objections elsewhere.",
        "Affirmative. We're all going to pretend this was the plan."
      ],
      "devops": [
        "Yes. Pipeline is green. Ship it.",
        "Approved. Rollback plan in place. Go.",
        "Confirmed. Monitoring dashboards ready.",
        "Proceed. Canary at 5%. Watch the metrics.",
        "Go for deploy. Runbook updated. Good luck.",
        "Affirmative. Infra ready. You're cleared for takeoff."
      ]
    }
  }
} as const;
